name: "Smoke test"
inputs:
  template:
    description: "Template to test"
    required: true

runs:
  using: "composite"
  steps:
    - name: "Checkout repository"
      uses: actions/checkout@v4

    - name: "Build template"
      shell: bash
      run: ${{ github.action_path }}/build.sh ${{ inputs.template }}

    - name: "Test template"
      shell: bash
      run: ${{ github.action_path }}/test.sh ${{ inputs.template }}
