name: "Smoke test"
inputs:
  template:
    description: "Template to test"
    required: true
  template-args:
    description: "Template arguments provided as a JSON object"
    required: false
    default: "{}"

runs:
  using: "composite"
  steps:
    - name: "Build template"
      shell: bash
      env:
        TEMPLATE_ID: ${{ inputs.template }}
        TEMPLATE_ARGS: ${{ inputs.template-args }}
      run: ${{ github.action_path }}/build.sh "${TEMPLATE_ID}" "${TEMPLATE_ARGS}"

    - name: "Test template"
      shell: bash
      run: ${{ github.action_path }}/test.sh ${{ inputs.template }}
